const pokerWords = [
    "aggro",
    "allin",
    "angle",
    "antes",
    "banks",
    "beats",
    "belly",
    "binks",
    "blank",
    "blast",
    "bleed",
    "blind",
    "block",
    "bluff",
    "board",
    "boats",
    "bombs",
    "break",
    "brick",
    "bring",
    "broke",
    "bucks",
    "bully",
    "burns",
    "burnt",
    "busts",
    "buyin",
    "calls",
    "cards",
    "catch",
    "chase",
    "cheat",
    "check",
    "chips",
    "chops",
    "click",
    "climb",
    "clock",
    "clubs",
    "color",
    "combo",
    "crabs",
    "crack",
    "deals",
    "dealt",
    "delay",
    "deuce",
    "dimes",
    "dirty",
    "donks",
    "doyle",
    "drawn",
    "draws",
    "ducks",
    "early",
    "eight",
    "faced",
    "faces",
    "felts",
    "field",
    "fifth",
    "fills",
    "final",
    "first",
    "fishy",
    "fives",
    "flash",
    "flats",
    "flips",
    "float",
    "flops",
    "flush",
    "folds",
    "force",
    "fours",
    "games",
    "grind",
    "gypsy",
    "hands",
    "heads",
    "heart",
    "hides",
    "holes",
    "hooks",
    "horse",
    "house",
    "hunts",
    "idiot",
    "image",
    "imply",
    "jacks",
    "joker",
    "kicks",
    "kings",
    "later",
    "leads",
    "leaks",
    "leave",
    "level",
    "light",
    "limit",
    "limps",
    "locks",
    "looks",
    "loose",
    "lucky",
    "lying",
    "match",
    "merge",
    "micro",
    "minus",
    "mixed",
    "money",
    "mucks",
    "multi",
    "nines",
    "nitty",
    "north",
    "nutty",
    "omaha",
    "opens",
    "orbit",
    "outer",
    "overs",
    "paint",
    "pairs",
    "penny",
    "plays",
    "poker",
    "polar",
    "posts",
    "probe",
    "props",
    "purse",
    "quads",
    "queen",
    "quits",
    "races",
    "racks",
    "rails",
    "raise",
    "rakes",
    "range",
    "ranks",
    "rates",
    "ratio",
    "reads",
    "rebuy",
    "rings",
    "river",
    "rocks",
    "rolls",
    "round",
    "royal",
    "scams",
    "scare",
    "scoop",
    "sells",
    "setup",
    "seven",
    "shark",
    "shill",
    "shoes",
    "short",
    "shove",
    "shows",
    "sixes",
    "skill",
    "slick",
    "small",
    "snaps",
    "solve",
    "south",
    "space",
    "spade",
    "spike",
    "split",
    "stack",
    "stake",
    "stand",
    "stare",
    "stars",
    "stays",
    "steal",
    "steam",
    "steel",
    "stick",
    "stole",
    "stone",
    "stuck",
    "studs",
    "study",
    "sucks",
    "suits",
    "super",
    "sweet",
    "swing",
    "table",
    "taint",
    "tanks",
    "tells",
    "texas",
    "third",
    "three",
    "tight",
    "tilts",
    "timer",
    "times",
    "token",
    "tough",
    "traps",
    "trash",
    "treys",
    "trips",
    "turbo",
    "turns",
    "twice",
    "under",
    "value",
    "vegas",
    "venmo",
    "verse",
    "wakes",
    "walks",
    "whale",
    "wheel",
    "witty",
    "wraps",
    "yacht",
    "zeros"
]
for (word of pokerWords) {
    if (!allWords.includes(word)) {
        allWords += word
        console.log(word)
    }
}

const width = window.innerWidth
const height = window.innerHeight
const keyPaddingRatio = 1/6
const keyWidth = width / (10 + 11 * keyPaddingRatio)
const keyHeight = keyWidth * 1.5
const keyPadding = keyWidth * keyPaddingRatio
const keyboardHeight = keyHeight * 3 + keyPadding * 3
const keyboardY = height - keyboardHeight
const keyboard = d3.select("body").append("svg").attr("width", width).attr("height", height).attr("id", "keyboard")
const letters = ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Z", "X", "C", "V", "B", "N", "M"]
const numLetters = [10, 9, 7]
const lettersOffset = [keyPadding, keyWidth * 0.5 + keyPadding * 1.5, keyWidth * 1.5 + keyPadding * 2.5]
var count = 0
for (let r = 0; r < 3; r++) {
    for (let i = 0; i < numLetters[r]; i++) {
        let x = lettersOffset[r] + (keyWidth + keyPadding) * i
        let y = keyboardY + keyHeight * r + keyPadding * r
        let key = keyboard.append("g")
            .attr("transform", "translate(" + x + "," + y + ")")
        
        key.append("rect")
            .attr("width", keyWidth)
            .attr("height", keyHeight)
            .attr("class", "key")
        
        key.append("text")
            .attr("x", keyWidth / 2)
            .attr("y", keyHeight * 0.7)
            .text(letters[count])
        
        count++
    }
}